export const display = document.getElementById('display')
export const clock = document.getElementById('clock')
export const music = document.getElementById('music')
export const minutes = document.getElementById('minutes')
export const seconds = document.getElementById('seconds')
